name: fiapeats-environment
services:
  fiapeats-api:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    image: tc-fiapeats-api:latest
    profiles: [app]
    restart: on-failure
    ports:
      - "8081:8081"