name: fiapeats-pagamento-environment
services:
  fiapeats-api:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    image: tc-fiapeats-api:latest
    profiles: [app, envfull]
    restart: on-failure
    ports:
      - "8081:8081"
    env_file: "variables/ambient.env"