server:
  port: 8081
  servlet:
    context-path: /fiapeats

spring:
  application:
    name: fiapeats

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

feign:
  pedido:
    url: http://localhost:8080/fiapeats
  autenticacao:
    url: https://api.mercadopago.com/oauth/token
  mercadoPago:
    urk: https://api.mercadopago.com