server:
  port: 8080
  servlet:
    context-path: /fiapeats

spring:
  application:
    name: /mspagamento

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

feign:
  mercadopago:
    autenticacao: ${FEIGN_MERCADOPAGO_AUTENTICACAO}
    pedido: ${FEIGN_MERCADOPAGO_PEDIDO}
  fiapeats:
    mspedido: ${FEIGN_FIAPEATS_MSPEDIDO}

url:
  notificacao: ${URL_NOTIFICACAO}
