server:
  port: 8081
  servlet:
    context-path: /fiapeats

spring:
  application:
    name: fiapeats

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

feign:
  pedido:
    url: ${FEIGN_PEDIDO_URL}
  autenticacao:
    url: ${FEIGN_AUTENTICACAO_URL}
  mercadoPago:
    urk: ${FEIGN_MERCADOPAGO_URL}