server:
  port: 8081
  servlet:
    context-path: /fiapeats

spring:
  application:
    name: fiapeats

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
